### ISSUE TITLE
Label color picker: give color picker in addition to defaults

### ISSUE THREAD

**Issue by damithc** [GitHubExtensions/Git-Labels#1]
The default color pallet is still useful. May be we can give our color picker in addition to the existing one

**Comment by damithc** [comment]
In fact I prefer to remove this feature for now, until we have a fully-baked feature dealing with label colors

**Comment by jiajunGit** [comment]
@damithc I have temporarily disabled the color picker in commit [ee4bf74](../commit/ee4bf74cfd03fbeaa72164b94b0f76d9f86c4d37)

**Comment by damithc** [comment]
Noted. Let me close this for now. Can reopen later if needed.
