### ISSUE TITLE
Keyboard shortcut hijacked by page

### ISSUE THREAD

**Issue by damithc** [GitHubExtensions/Git-Labels#10]
I noticed that sometimes,  both the `Labels` widget in the page and our panel respond to the keyboard shortcut and the the page's widget take precedence over overs. Perhaps we should have our own shortcut e.g. `Shift + L`?

**Comment by damithc** [comment]
To reproduce, hit `L` as soon as the page is loaded, before our own panel appears.

**Comment by jiajunGit** [comment]
Added a fix in commit [66b85d8](../commit/66b85d82182745d26ec2f21dfb86e19a617a8e48). Could you check to see if this issue is resolved on your side? Thanks!

**Comment by damithc** [comment]
Seems to be fixed now.
