### ISSUE TITLE
Package as a proper chrome extension

### ISSUE THREAD

**Issue by damithc** [GitHubExtensions/Git-Labels#12]
as per subject

**Comment by jiajunGit** [comment]
@damithc You can find the packed chrome extension **Git-Labels.crx** at [/bin/](../tree/master/bin). I have also added [installation instructions](../#option-1-using-packed-google-chrome-extension) in the README.md (**Remove the unpacked version before installing the packed version to prevent any conflicts**)

**Comment by damithc** [comment]
I meant like an extension that I get from the Chrome app store and updates automatically when there is a new version. :-p
Chrome is auto-disabling the packed version, so I have to go back to the unpacked version (which gives me a warning every time I start Chrome)

**Comment by jiajunGit** [comment]
@damithc Ok, I will see if i can get this on the chrome app store.

**Comment by jiajunGit** [comment]
@damithc The extension is now in the app store at <https://chrome.google.com/webstore/detail/git-labels/ipfflmlpojlbhcfapenihefpifipecal>

**Comment by damithc** [comment]
Nice 💯
