### ISSUE TITLE
Support adding labels to pull requests

### ISSUE THREAD

**Issue by damithc** [GitHubExtensions/Git-Labels#5]
Currently, only issues can use the plugin

**Comment by damithc** [comment]
elevating priority because I use status labels for pull requests a lot.

**Comment by jiajunGit** [comment]
Fixed in commits [2ad9c35](../commit/2ad9c35cfad30fc4d43b61e50a9c155149d0947a) and [08a2c01](../commit/08a2c0146f80297429d4e3b2dbda9d60393111f7)

**Comment by damithc** [comment]
I was looking forward to this 💯 👍
