### ISSUE TITLE
Enter key should select the top label in search results

### ISSUE THREAD

**Issue by damithc** [GitHubExtensions/Git-Labels#8]
To apply labels `foo` and `bar`
Current:
1. type `foo`
1. press `down`
1. press `space`
1. type `bar`
1. press `down`
1. press `space`
1.  press enter

Suggested:
1. type `foo`
1. ~~press `down`~~ this is covered in another issue #3 
1. press `space`
1. type `bar`
1. ~~press `down`~~ this is covered in another issue #3 
1. ~~**press `space`**~~
1.  press enter

**Comment by jiajunGit** [comment]
Functionality added in commit [58cca19](../commit/58cca191feef5b9aff02f9a08b48ca79425910ed)

**Comment by damithc** [comment]
@jiajunGit You can close the issue if fixed. In fact you can mention `fixes #8` in the commit message itself and the issue will auto close when the commit is pushed.

**Comment by damithc** [comment]
Fixed 👍
