### ISSUE TITLE
Shortcut key doesn't work if the page is reached using back navigation

### ISSUE THREAD

**Issue by damithc** [GitHubExtensions/Git-Labels#9]
Steps:
1. Go to a pull request page
2. Click on the `files` tab
3. Use the `back` button of the browser to navigate back to the previous page
4. Hit `L` key

The labels panel does not appear as expected.

**Comment by jiajunGit** [comment]
@damithc I have fixed this bug for all issue pages in commit [35068ce](../commit/35068ce397b8eddffb1f02346ffde77511e56174). Could you check if this bug is resolved on your side? Thanks

**Comment by damithc** [comment]
Yes, seems to be fixed. closing.
